version: '3'

services:
  scripts:
    build:
      context: ./scripts
      dockerfile: Dockerfile
      
    depends_on:
      - sqldata
      - postfix

    network_mode: bridge


  sqldata: 
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "crypto"

    volumes: 
      - ./data:/var/lib/mysql

    network_mode: bridge



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    network_mode: bridge
    depends_on:
      - sqldata

  postfix:
    image: juanluisbaptiste/postfix:latest
    network_mode: bridge

    environment: 
      SMTP_SERVER: smtp.gmail.com 
      SMTP_USERNAME: (Insert username of email)
      SMTP_PASSWORD: (Insert generated app password)
      SERVER_HOSTNAME: localhost
      SERVER_NETWORKS: 172.17.0.1/24
