version: '3'

services:
  scripts:
    build:
      context: ./scripts
      dockerfile: Dockerfile
      
    depends_on:
      - sqldata

    networks: 
      - mynet
    privileged: true
    environment: 
      SMTP_SERVER: smtp.gmail.com 
      SMTP_USERNAME: (Insert gmail address)
      SMTP_PASSWORD: (Insert generated app password)
      SERVER_HOSTNAME: docker.cryptoservice


  sqldata: 
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "crypto"

    volumes: 
      - ./data:/var/lib/mysql

    networks: 
      - mynet



  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
      - mynet
    depends_on:
      - sqldata

networks:
  mynet:
    driver: bridge
    ipam: 
      driver: default
      config: 
        - subnet: "172.16.0.0/24"
    
